name: Validate
on: [push, pull_request]
jobs:
  prettier-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Prettier Code Check
        uses: stefanzweifel/prettier-action@v2
        with:
          files: .
          prettierOptions: --check

