name: Validate
on: [push, pull_request]
jobs:
  prettier-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
# Note: use fetch depth to get previous commit if needed
      
      - name: Prettier Code Check
	      uses: creyD/prettier_action@v4.2		
        with:		
          prettier_options: --write .

